### ISSUE TITLE
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory /home/mustafa/ckpt

### ISSUE THREAD

**Issue by syedmustafa54** [run-youngjoo/SC-FEGAN#30]
I have changed the yml file to `CKPT_DIR: '/home/mustafa/ckpt'
` inside this dir there is model file `SC-FEGAN.ckpt.data-00000-of-00001` and index file `SC-FEGAN.ckpt.index`
error is 
```c:305] kernel version seems to match DSO: 418.39.0
Model loaded from /home/mustafa/ckpt....start
Traceback (most recent call last):
  File "demo.py", line 234, in <module>
    ex = Ex(model, config)
  File "demo.py", line 22, in __init__
    self.model.load_demo_graph(config)
  File "/media/mustafa/ubuntu_backup/Projects/gan/SC-FEGAN/model.py", line 111, in load_demo_graph
    var_value = tf.contrib.framework.load_variable(ckpt_path, from_name)
  File "/home/mustafa/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/framework/python/framework/checkpoint_utils.py", line 79, in load_variable
    reader = load_checkpoint(checkpoint_dir)
  File "/home/mustafa/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/framework/python/framework/checkpoint_utils.py", line 62, in load_checkpoint
    "given directory %s" % filepattern)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory /home/mustafa/ckpt
```

**Comment by JoYoungjoo** [comment]
Make the './ckpt' dir in SC-FEGAN project folder plz.

**Comment by MichealJl** [comment]
遇到同样的问题 请问你解决了么

**Comment by MichealJl** [comment]
Have you solved this problem

**Comment by syedmustafa54** [comment]
Yes I have solved this issue

**Comment by MichealJl** [comment]
Please tell me how you solved it.

**Comment by syedmustafa54** [comment]
I create ckpt dir and pasted the model files there

**Comment by MichealJl** [comment]
I am the CKPT directory created under the SC-FEGAN project, but I still report an error.

**Comment by MichealJl** [comment]
Can I see your demo.yaml？

**Comment by syedmustafa54** [comment]
you need to give `SC-FEGAN.ckpt` name on yaml here is my yaml
```
INPUT_SIZE: 512
BATCH_SIZE: 1

GPU_NUM: 1

# directories
CKPT_DIR: 'ckpt/SC-FEGAN.ckpt'
```

**Comment by MichealJl** [comment]
Thank you for your help. I think I've found the reason.

**Comment by syedmustafa54** [comment]
What was it write it down so this can help others

**Comment by chenthefool** [comment]
I have just solved this question. this is my filename: **model.ckpt-100000.data-00000-of-00001** and shell command:  ``` python run pretraining --init_checkpoint=./ckpt/model.ckpt-100000 ```  
so, when you enter the file name, you just ignore the **.data-00000-of-00001**

**Comment by JayJongyoul** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2021-04-22T14:31:55
          
          
            * Subject : 
Re: [run-youngjoo/SC-FEGAN] ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory /home/mustafa/ckpt (#30)
          
          
            
              
                * Remote host said : 
              
              
                
Requested action not taken: mailbox unavailable
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.

**Comment by gerwindekruijf** [comment]
I fixed the error, your files should be called "model.ckpt.....", in my case it was something like "bert-model.ckpt" which does not work. It does not matter if there are other files, such as config.json, in your directory as long as the checkpoints are named "model.ckpt....."

**Comment by JayJongyoul** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2022-05-24T20:51:45
          
          
            * Subject : 
Re: [run-youngjoo/SC-FEGAN] ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory /home/mustafa/ckpt (#30)
          
          
            
              
                * Remote host said : 
              
              
                
Requested action not taken: mailbox unavailable
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.
