### ISSUE TITLE
The generator seems didn't use "mask" information.

### ISSUE THREAD

**Issue by penguinbing** [run-youngjoo/SC-FEGAN#40]
As the title said. Thank you.

**Comment by abtExp** [comment]
It does use the mask, the x (input) is a combination of the sketch, color, noise, mask and makes image.
The generator produces the completed image which is then multiplied with the mask to obtain only the masked portion from the generated image and the unmasked image is kept the same, thus reducing the noise introduced by the generator.

**Comment by penguinbing** [comment]
Thank you very much. The generator input parameters were misleading.
